python ilastik_classifier/filter_nuclei_with_ilastik_mask.py \
  --json-dir "/mnt/f/data/HandE/sow1885_n201/nucsegai_pred/json" \
  --typeprob-dir "/mnt/f/data/HandE/sow1885_n201/nucsegai_pred/typeprob" \
  --artifact-h5-dir "/mnt/j/HandE/results/ilastik/mask_artifact" \
  --rbc-h5-dir "/mnt/j/HandE/results/ilastik/mask_rbc" \
  --out-json-dir "/mnt/f/data/HandE/sow1885_n201/nucsegai_pred/json_filtered" \
  --out-typeprob-dir "/mnt/f/data/HandE/sow1885_n201/nucsegai_pred/typeprob_filtered" \
  --artifact-threshold 0.5 \
  --artifact-fraction-threshold 0.5\
  --rbc-threshold 0.5 \
  --rbc-fraction-threshold 0.5